# Generated by Django 6.0 on 2026-01-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.BigIntegerField()),
                ('mfg_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.productvariant')),
            ],
        ),
    ]
