# Generated by Django 6.0 on 2026-01-01 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.BigIntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.BigIntegerField()),
                ('profile_pic', models.CharField(default='')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categories')),
            ],
        ),
    ]
