# Generated by Django 6.0 on 2026-01-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.BigIntegerField(default=0),
        ),
    ]
