# Generated by Django 6.0 on 2026-01-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='profile_pic',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
