# Generated by Django 6.0 on 2026-01-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productvariant_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.BigIntegerField(),
        ),
    ]
